### ISSUE TITLE
Add "No row checked" error

### ISSUE THREAD

**Issue by meeple142** [byuitechops/csv-mapleta-to-d2l#3]
We were going to have it so that blank meant I don't want to import it, but the go button does not show up till they are filled in. 

So we could use checkboxes or have the go button show up too when the file is up loaded.

**Comment by g-mips** [comment]
I changed it so that the go button will appear when the table appears now. However, I'm not closing this yet because I'm not entirely sure if that's exactly what you want. My thought is that we will have it check for the rows that are checked. If a row is checked then it's included.

Possible error displays to the user:
- No row is checked

Possible warning displays to the user:
- Row is not checked, but there is information there.
- Row is checked, but there is no information there.

**Comment by g-mips** [comment]
This is now checked.
